### ISSUE TITLE
Install using HACS, no configuration available

### ISSUE THREAD

**Issue by mvandenabeele** [kotope/valloxesp#13]
Hi

I managed to add vallox2mqtt latest release to Home Assistant 2021.12.9 but it doesn't add entities and I'm not able to change configuration settings. I guess I'm doing something wrong, but I don't know what. I must add, ESP32 is already running but not connected to my ventilation unit. I first wanted to check communication channels because I switched to ESP32 and want to use Serial2 instead of the default serial port.

Any help would be very much appreciated.

**Comment by kotope** [comment]
Have you done it like this:
– HACS -> add custom repository -> https://github.com/kotope/valloxesp.git
– Install vallox2mqtt
– go to configuration -> devices -> integrations -> + add integration
– search for vallox2mqtt and click ok
–> configuration flow should start at this point

**Comment by mvandenabeele** [comment]
I thought I had done this but couldn't find the vallox2mqtt integration. Did it again yesterday, and it's up and running now.

Thanks again!
