### ISSUE TITLE
HA 2022.3 update -> issues with the integration

### ISSUE THREAD

**Issue by lassikos** [kotope/valloxesp#16]
Hi,

Just updated HA to 2022.3 and seems that something is changed again so that this integration does not work:

![image](https://user-images.githubusercontent.com/85075211/156452972-ce8d58f8-65af-4e38-9f90-13084ef6c90c.png)

**Comment by kotope** [comment]
Thanks for pointing this out. Just updated myself as well and noticed the same.
I will fix it this evening.

**Comment by kotope** [comment]
Fixed with #17
