### ISSUE TITLE
Deprecation Items as per Homeassistant log

### ISSUE THREAD

**Issue by captaindork** [kotope/valloxesp#36]
Hi there,
opening this issue as per HA log:

HVAC_MODE_HEAT was used from vallox2mqtt, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.HEAT instead, please create a bug report at https://github.com/kotope/valloxesp/issues
HVAC_MODE_FAN_ONLY was used from vallox2mqtt, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.FAN_ONLY instead, please create a bug report at https://github.com/kotope/valloxesp/issues
CURRENT_HVAC_OFF was used from vallox2mqtt, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACAction.OFF instead, please create a bug report at https://github.com/kotope/valloxesp/issues
CURRENT_HVAC_HEAT was used from vallox2mqtt, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACAction.HEATING instead, please create a bug report at https://github.com/kotope/valloxesp/issues
CURRENT_HVAC_FAN was used from vallox2mqtt, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACAction.FAN instead, please create a bug report at https://github.com/kotope/valloxesp/issues

TEMP_CELSIUS was used from vallox2mqtt, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please create a bug report at https://github.com/kotope/valloxesp/issues

Thanks for looking into this!

**Comment by kotope** [comment]
Thanks for opening issue 👍 . These deprecations will be fixed for the next release
