### ISSUE TITLE
better names for temperature variables

### ISSUE THREAD

**Issue by priiduonu** [kotope/valloxesp#6]
I would suggest more precise names for temperature variables:

- "incoming" -> "supply"
- "inside" -> "indoor"
- "outside" -> "outdoor"

"exhaust" is correct.

![temperature_names](https://user-images.githubusercontent.com/5614724/120696203-ef20e580-c4b4-11eb-8561-4927073ee60d.png)

Sources:
https://www.vallox.com/files/3304/Manual_Vallox_MyVallox_Control_ENG.pdf
https://www.vallox.com/?s=156&l=en

Should be easy fix by search/replace when keeping correct capitalization. Requires user configuration edits, though.

**Comment by kotope** [comment]
Closing old issues. 
Going with the current implementation regarding this.
